from typing import NewType

Path = NewType('Path', str)
FullPath = NewType('FullPath', Path)

def basename(path: str) -> str: ...
def dirname(fullPath: FullPath) -> FullPath: ...
def exists(fullPath: FullPath) -> bool: ...
def getmtime(fullPath: FullPath) -> float: ...
def getsize(fullPath: FullPath) -> int: ...
def isdir(fullPath: FullPath) -> bool: ...
def join(dirPath: FullPath, realpath: str) -> FullPath: ...
def normpath(fullPath: FullPath) -> FullPath: ...
def realpath(fullPath: FullPath) -> FullPath: ...
def relpath(fullPath: FullPath, dirPath: FullPath) -> str: ...
